import Image1 from "../../img/memes/mem1.jpg"
import Image2 from "../../img/memes/mem2.jpg"
import Image3 from "../../img/memes/mem3.jpg"
import Image4 from "../../img/memes/mem4.jpg"
import Image5 from "../../img/memes/mem5.png"
import Image6 from "../../img/memes/mem6.png"
import Image7 from "../../img/memes/mem7.jpg"
import Image8 from "../../img/memes/mem8.jpg"
import Image9 from "../../img/memes/mem9.png"
import Image10 from "../../img/memes/mem10.png"
import Image11 from "../../img/memes/mem11.png"
import Image12 from "../../img/memes/mem12.png"
import Image13 from "../../img/memes/mem13.png"
import Image14 from "../../img/memes/mem14.png"
import Image15 from "../../img/memes/mem15.png"

export default [Image1,Image2,Image3,Image4,Image5,Image6,Image7,Image8,Image9,Image10,Image11,Image12,Image13, Image14, Image15]